baseurl = "/"
languageCode = "en-US"
title = "Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.JPG" # change picture
  author = "Maria Dolak"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "s1737523@ed.ac.uk"
  GitHub        = "mdolak"
  LinkedIn      = "mariadolak"
  Instagram     = "mary_dolak"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "papers"
  identifier = "papers"
  weight = 200
  url = "/papers"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 400
  url = "/resume.pdf"
